In [1]:
import pandas as pd

prices = pd.read_csv("../data/raw/prices.csv", index_col=0, parse_dates=True)

prices.head()

                   GLD         IWM        QQQ         SPY        TLT
Date
2015-01-02  114.080002  102.786995  94.665070  170.125015  93.367279
2015-01-05  115.800003  101.412796  93.276443  167.052628  94.833992
2015-01-06  117.120003   99.658363  92.025764  165.479126  96.542625
2015-01-07  116.430000  100.885612  93.212097  167.541245  96.351944
2015-01-08  115.940002  102.596832  94.996132  170.514175  95.076004

In [2]:
prices.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 2852 entries, 2015-01-02 to 2026-05-06
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   GLD     2852 non-null   float64
 1   IWM     2852 non-null   float64
 2   QQQ     2852 non-null   float64
 3   SPY     2852 non-null   float64
 4   TLT     2852 non-null   float64
dtypes: float64(5)
memory usage: 133.7 KB

In [3]:
prices.describe()

               GLD          IWM          QQQ          SPY          TLT
count  2852.000000  2852.000000  2852.000000  2852.000000  2852.000000
mean    174.117556   162.304282   275.150547   347.476483   100.354110
std      75.947764    44.575096   154.254187   150.463024    15.777042
min     100.500000    83.118317    89.474037   154.558777    74.265877
25%     121.169998   125.838957   142.530945   223.303093    88.763258
50%     161.650002   153.653580   261.178314   309.626068    95.699455
75%     182.952499   199.348381   367.635117   429.982140   107.784180
max     495.899994   286.799988   695.770020   733.830017   143.789993